site_name: Hackathon Management System — Лабораторная 1
site_author: Лаптев Егор
site_description: Отчёт по лабораторной работе 1 — система для проведения хакатонов

nav:
  - Главная: index.md
  - Лабораторная 1: lab1/index.md
  - Лабораторная 2: lab2/index.md
  - Лабораторная 3: lab3/index.md

theme:
  name: material
