site_name: Hackathon Management System — Лабораторная 1
site_author: Лаптев Егор
site_description: Отчёт по лабораторной работе 1 — система для проведения хакатонов

nav:
  - Главная: index.md
  - Практика 1: pr1.md
  - Практика 2: pr2.md
  - Практика 3: pr3.md
  - Лабораторная 1: lr1.md

theme:
  name: material
